### ISSUE TITLE
[question] Porting to another framework 

### ISSUE THREAD

**Issue by OneCricketeer** [streamthoughts/azkarra-streams#28]
I understand this library uses undertow and Rest-assured.

What would you estimate the level of difficulty would be in porting to another framework? 

Say Quarkus or getting Kafka Streams functionality added into [dropwizard-kafka](https://github.com/dropwizard/dropwizard-kafka) (JAX-RS based)

**Comment by fhussonnois** [comment]
Hi @cricket007 

It's a broad question, but migrating Azkarra to use another solution than Undertow as an embedded http server or to use JAX-RS shouldn't be difficult.

Azkarra uses java ServiceLoader to discover the implementation of [EmbeddedHttpServerProvider](https://github.com/streamthoughts/azkarra-streams/blob/master/azkarra-api/src/main/java/io/streamthoughts/azkarra/api/spi/EmbeddedHttpServerProvider.java) to be used.

All REST services are provided by the class [LocalAzkarraStreamsService](https://github.com/streamthoughts/azkarra-streams/blob/master/azkarra-runtime/src/main/java/io/streamthoughts/azkarra/runtime/service/LocalAzkarraStreamsService.java). Actually, the module azkarra-server mostly contains HTTP handlers and Jackson serializers.

Quarkus already has a good extension for Kafka Streams which parts of Azkarra whould you like to migrate ?

**Comment by cricket007** [comment]
Thanks for the response. 

I would likely target the linked Dropwizard module / JAX-RS since the Kafka Streams functionality is missing there at the moment (and I currently use an internal implementation of a Dropwizard Kafka bundle at work), but think it'd be useful to build over an existing, public solution. 

> Quarkus already has a good extension for Kafka Streams

You might be right, I haven't taken too much time to look at any more than the basic guide. https://quarkus.io/guides/kafka-streams

> the module azkarra-server mostly contains HTTP handlers and Jackson serializers.

So, that makes me think that Dropwizard-Kafka could potentially be a wrapper around the HTTP request/response handlers written here?

Or a Jersey module could be added here in place of Undertow?

**Comment by fhussonnois** [comment]
Currently, it's not possible to inject a new Undertow HTTPHandler without modifying the java class : [UndertowEmbeddedServer](https://github.com/streamthoughts/azkarra-streams/blob/0f209bf7a39b4d0eca38b3f013b0f64676f8ac0c/azkarra-server/src/main/java/io/streamthoughts/azkarra/http/UndertowEmbeddedServer.java). 

I've identified two possible solutions:

**1/**

 Implementing a new EmbeddedHttpServer by using the framework of your choice (Jetty/Undertow + Jersey/RESTEasy) - but you will have to re-implement all existing REST endpoints.

**2/** 
Modifying the existing UndertowEmbeddedServer to be able to enable/disable a ServletHandler into the Undertow request handler chain. Then, Azkarra should provide a mechansim for developer to register new JAX-RS resources. This maybe quite similar to Kafka Connect (https://cwiki.apache.org/confluence/display/KAFKA/KIP-285%3A+Connect+Rest+Extension+Plugin).


**About Quarkus Integration**

It should be possible to simply register as Quarkus beans the StreamsExecutionEnvironment and TopologyProvider classes and build the AzkarraContext programmatically. But, you will still have to re-implement the REST endpoints. Also, Azkarra UI has a dedicated module so that you can easily add the azkarra-ui dependency to your project if needed.

NOTE: I've also the idea to implement a Java agent that can be add to an existing project for wrapping all KafkaStreams instances existing into the JVM in order to provides some Azkarra features.

**Comment by cricket007** [comment]
Since Dropwizard is Jersey based and Quarkus is (only?) Vert.x, I assumed that the HTTP endpoints would need rewritten. So, my question then is how decoupled is the processing logic from those "service/resource" classes, and where would one look for extending that if so?

> This maybe quite similar to Kafka Connect

I have some experience with that via Schema Registry (same mechanism). I think those extensions are for Jetty Server

> Azkarra UI has a dedicated module so that you can easily add the azkarra-ui dependency to your project if needed

Cool, will definitely need to look at that
